apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhnmrte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhnmrte
  template:
    metadata:
      labels:
        app: dhnmrte
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: dhnmrte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ab138d1b-74b1-46dc-bb58-0307b8d85952"
        - name: Vless_Path
          value: "/vlhuy7885"
        - name: Vmess_UUID
          value: "ab138d1b-74b1-46dc-bb58-0307b8d85952"
        - name: Vmess_Path
          value: "/vm6gy6756"
        - name: Share_Path
          value: "/v2link"
